version: '3'
services:
  web:
    container_name: web
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./application:/app
    env_file:
      - ./application/.env.local
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge